export const constants = {
  //auth
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  VERIFY_REQUEST: 'VERIFY_REQUEST',
  VERIFY_SUCCESS: 'VERIFY_SUCCESS',
  VERIFY_FAILURE: 'VERIFY_FAILURE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // categories
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
  ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
  ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
  ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
  UPDATE_CATEGORY_REQUEST: 'UPDATE_CATEGORY_REQUEST',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_FAILURE: 'UPDATE_CATEGORY_FAILURE',

  // products
  GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
  GET_PRODUCT_BY_ID_REQUEST: 'GET_PRODUCT_BY_ID_REQUEST',
  GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',
  GET_PRODUCT_BY_ID_FAILURE: 'GET_PRODUCT_BY_ID_FAILURE',
  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILURE: 'UPDATE_PRODUCT_FAILURE',
  ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
  CHANGE_PRODUCT_STATUS_SUCCESS: 'CHANGE_PRODUCT_STATUS_SUCCESS',
  CHANGE_PRODUCT_STATUS_REQUEST: 'CHANGE_PRODUCT_STATUS_REQUEST',
  CHANGE_PRODUCT_STATUS_FAILURE: 'CHANGE_PRODUCT_STATUS_FAILURE',

  // profile
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',

  // shop
  GET_SHOP_REQUEST: 'GET_SHOP_REQUEST',
  GET_SHOP_SUCCESS: 'GET_SHOP_SUCCESS',
  GET_SHOP_FAILURE: 'GET_SHOP_FAILURE',
  ADD_SHOP_REQUEST: 'ADD_SHOP_REQUEST',
  ADD_SHOP_SUCCESS: 'ADD_SHOP_SUCCESS',
  ADD_SHOP_FAILURE: 'ADD_SHOP_FAILURE',
  UPDATE_SHOP_REQUEST: 'UPDATE_SHOP_REQUEST',
  UPDATE_SHOP_SUCCESS: 'UPDATE_SHOP_SUCCESS',
  UPDATE_SHOP_FAILURE: 'UPDATE_SHOP_FAILURE',

  //brand
  GET_BRAND_REQUEST: 'GET_BRAND_REQUEST',
  GET_BRAND_SUCCESS: 'GET_BRAND_SUCCESS',
  GET_BRAND_FAILURE: 'GET_BRAND_FAILURE',
  ADD_BRAND_REQUEST: 'ADD_BRAND_REQUEST',
  ADD_BRAND_SUCCESS: 'ADD_BRAND_SUCCESS',
  ADD_BRAND_FAILURE: 'ADD_BRAND_FAILURE',
  UPDATE_BRAND_REQUEST: 'UPDATE_BRAND_REQUEST',
  UPDATE_BRAND_SUCCESS: 'UPDATE_BRAND_SUCCESS',
  UPDATE_BRAND_FAILURE: 'UPDATE_BRAND_FAILURE',

  // employee
  ADD_EMPLOYEE_REQUEST: 'ADD_EMPLOYEE_REQUEST',
  ADD_EMPLOYEE_SUCCESS: 'ADD_EMPLOYEE_SUCCESS',
  ADD_EMPLOYEE_FAILURE: 'ADD_EMPLOYEE_FAILURE',

  NOTIFICATION_SUCCESS: 'success',
  NOTIFICATION_ERROR: 'error',
  NOTIFICATION_WARNING: 'warning'
}
